# Font Customization
font_size           11
font_family         LiterationMono Nerd Font

# Window Border
window_margin_width 6

# Scroll Factor
touch_scroll_multiplier 12

# BEGIN_KITTY_THEME
# Matugen
include current-theme.conf
# END_KITTY_THEME
