-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local image = "/home/crdcamp/.dotfiles/Pictures/Wallpapers/SnowMountain.png"

local background = "rgba(141318ff)"

local error = "rgba(ffb4abff)"

local error_container = "rgba(93000aff)"

local inverse_on_surface = "rgba(322f35ff)"

local inverse_primary = "rgba(63568fff)"

local inverse_surface = "rgba(e6e1e9ff)"

local on_background = "rgba(e6e1e9ff)"

local on_error = "rgba(690005ff)"

local on_error_container = "rgba(ffdad6ff)"

local on_primary = "rgba(34275eff)"

local on_primary_container = "rgba(e8deffff)"

local on_primary_fixed = "rgba(1f1048ff)"

local on_primary_fixed_variant = "rgba(4b3e76ff)"

local on_secondary = "rgba(322e41ff)"

local on_secondary_container = "rgba(e7def8ff)"

local on_secondary_fixed = "rgba(1d192bff)"

local on_secondary_fixed_variant = "rgba(494458ff)"

local on_surface = "rgba(e6e1e9ff)"

local on_surface_variant = "rgba(cac4cfff)"

local on_tertiary = "rgba(492533ff)"

local on_tertiary_container = "rgba(ffd9e4ff)"

local on_tertiary_fixed = "rgba(31111eff)"

local on_tertiary_fixed_variant = "rgba(633b49ff)"

local outline = "rgba(938f99ff)"

local outline_variant = "rgba(48454eff)"

local primary = "rgba(cdbdffff)"

local primary_container = "rgba(4b3e76ff)"

local primary_fixed = "rgba(e8deffff)"

local primary_fixed_dim = "rgba(cdbdffff)"

local scrim = "rgba(000000ff)"

local secondary = "rgba(cbc3dcff)"

local secondary_container = "rgba(494458ff)"

local secondary_fixed = "rgba(e7def8ff)"

local secondary_fixed_dim = "rgba(cbc3dcff)"

local shadow = "rgba(000000ff)"

local source_color = "rgba(59536aff)"

local surface = "rgba(141318ff)"

local surface_bright = "rgba(3a383eff)"

local surface_container = "rgba(201f24ff)"

local surface_container_high = "rgba(2b292fff)"

local surface_container_highest = "rgba(36343aff)"

local surface_container_low = "rgba(1c1b20ff)"

local surface_container_lowest = "rgba(0f0d13ff)"

local surface_dim = "rgba(141318ff)"

local surface_tint = "rgba(cdbdffff)"

local surface_variant = "rgba(48454eff)"

local tertiary = "rgba(eeb8c9ff)"

local tertiary_container = "rgba(633b49ff)"

local tertiary_fixed = "rgba(ffd9e4ff)"

local tertiary_fixed_dim = "rgba(eeb8c9ff)"
