-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- source = monitors.conf -> requires manual conversion
-- local monitors = require("monitors")
-- TODO: convert monitors.conf to .lua and use require()

-- source = variables.conf -> requires manual conversion
-- local variables = require("variables")
-- TODO: convert variables.conf to .lua and use require()

-- source = lookAndFeel.conf -> requires manual conversion
-- local lookAndFeel = require("lookAndFeel")
-- TODO: convert lookAndFeel.conf to .lua and use require()

-- source = keyBindings.conf -> requires manual conversion
-- local keyBindings = require("keyBindings")
-- TODO: convert keyBindings.conf to .lua and use require()

-- source = windowRules.conf -> requires manual conversion
-- local windowRules = require("windowRules")
-- TODO: convert windowRules.conf to .lua and use require()

--################

--## AUTOSTART ###

--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)







--############################

--## ENVIRONMENT VARIABLES ###

--############################

hl.env("XCURSOR_SIZE", 20)

hl.env("HYPRCURSOR_SIZE", 20)

hl.env("CLUTTER_BACKEND", "wayland")

-- GDK

hl.env("GDK_BACKEND", "wayland,x11,*")

--env = GDK_SCALE=2

-- Electron

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

-- XDG

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-- Qt

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

--env = QT_AUTO_SCREEN_SCALE_FACTOR,1.5

hl.env("QT_QPA_PLATFORM", "wayland")

hl.env("QT_QPA_PLATFORM", "wayland;xcb")

--##################

--## PERMISSIONS ###

--##################

-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly

-- for security reasons

-- ecosystem {

--   enforce_permissions = 1

-- }

-- Might need these three later

-- permission = /usr/(bin|local/bin)/grim, screencopy, allow

-- permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow

-- permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

--############

--## INPUT ###

--############

hl.config({
    input = {
        kb_layout = "us",
        kb_options = "grp:win_space_toggle",
        follow_mouse = 1,
        -- Mouse sensitivity
        sensitivity = 0,
        accel_profile = "flat",
        touchpad = {
            natural_scroll = true,
            scroll_factor = 0.3,
        },
    },
})

-- Touchpad Sentitivity

hl.device({
    name = "dll0945:00-27c6:01e0-touchpad",
    sensitivity = 0.6,
    accel_profile = "flat",
})

hl.gesture({
    ["fingers"] = 3,
    ["direction"] = "horizontal",
    ["action"] = "workspace",
})

hl.config({
    general = {
        resize_on_border = true,
        extend_border_grab_area = 7,
    },
})

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

hl.config({
    misc = {
        focus_on_activate = true,
    },
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("waybar")
    hl.exec_cmd("swaync")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)
