-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--##################

--## KEYBINDINGS ###

--##################

local mainMod = "SUPER"

-- ESSENTIALS

hl.bind(mainMod .. " + " .. "return", hl.dsp.exec_cmd("$terminal"))

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "ESCAPE", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit"))

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("$terminal --title yazi $fileManager"))

hl.bind(mainMod .. " + " .. "ESCAPE", hl.dsp.exec_cmd("hyprlock"))

-- WINDOW MANAGEMENT

-- Move window focus

hl.bind(mainMod .. " + " .. "H", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "L", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "K", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "J", hl.dsp.focus({ direction = "down" }))

-- Move windows with keys

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "H", hl.dsp.window.move({ direction = "left" }))

-- Move window left

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "L", hl.dsp.window.move({ direction = "right" }))

-- Move window right

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "K", hl.dsp.window.move({ direction = "up" }))

-- Move window up

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "J", hl.dsp.window.move({ direction = "down" }))

-- Move window down

-- Resize windows with keys

hl.bind("SUPER + left", hl.dsp.window.resize({ x = -35, y = 0, relative = true }), { repeating = true })

hl.bind("SUPER + right", hl.dsp.window.resize({ x = 35, y = 0, relative = true }), { repeating = true })

hl.bind("SUPER + up", hl.dsp.window.resize({ x = 0, y = 35, relative = true }), { repeating = true })

hl.bind("SUPER + down", hl.dsp.window.resize({ x = 0, y = -35, relative = true }), { repeating = true })

-- Fullscreen

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen({ mode = 1 }))

-- Expand to full screen

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "F", hl.dsp.window.fullscreen())

-- Fill entire screen

hl.bind(mainMod .. " + " .. "D", hl.dsp.layout("togglesplit"))

-- Split windows

-- Move/resize windows with mouse/touchpad

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

-- TODO: manual review (unknown dispatcher: resizewindow)
-- hl.bind(mainMod .. " + " .. "+ -", hl.dsp.resizewindow())

-- Float window management

hl.bind(mainMod .. " + " .. "V", hl.dsp.window.float())

-- Individual window float

-- TODO: manual review (unknown dispatcher: workspaceopt)
-- hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "V", hl.dsp.workspaceopt("allfloat"))

-- Float all windows in active workspace

hl.bind(mainMod .. " + " .. "C", hl.dsp.window.center())

-- Center float window

-- NOTIFICATION CENTER

hl.bind(mainMod .. " + " .. "N", hl.dsp.exec_cmd("swaync-client -t -sw"))

-- ROFI

hl.bind(mainMod .. " + " .. "SPACE", hl.dsp.exec_cmd("$searchWindows"))

-- Search windows

hl.bind(mainMod .. " + " .. "M", hl.dsp.exec_cmd("$openControlCenter"))

--bind = $mainMod, SPACE, exec, $searchApps

-- SHOW/HIDE WAYBAR

hl.bind(mainMod .. " + " .. "W", hl.dsp.exec_cmd("killall -SIGUSR1 waybar"))

-- WALLPAPER/THEME CHANGE

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "W", hl.dsp.exec_cmd("$selectWallpaper"))

-- BROWSER SHORTCUTS

hl.bind(mainMod .. " + " .. "I", hl.dsp.exec_cmd("$browser"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Y", hl.dsp.exec_cmd("$browser https://youtube.com"))

-- YouTube shortcut

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "U", hl.dsp.exec_cmd("$browser https://mail.google.com/mail"))

-- Gmail shortcut

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "T", hl.dsp.exec_cmd("$browser https://calendar.google.com/calendar/u/0/r"))

-- Google Calendar shortcut

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "O", hl.dsp.exec_cmd("$browser https://github.com/"))

-- GitHub shortcut

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "I", hl.dsp.exec_cmd("$browser https://claude.ai/new"))

-- Claude shortcut

-- IDE

hl.bind(mainMod .. " + " .. "O", hl.dsp.exec_cmd("$IDE"))

-- ENTERTAINMENT

hl.bind(mainMod .. " + " .. "P", hl.dsp.exec_cmd("$music"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "G", hl.dsp.exec_cmd("$steam"))

-- WORKSPACE MANAGEMENT

-- Switch workspaces

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- VOLUME, BRIGHTNESS, AND AUDIO

-- Volume keys

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { repeating = true, locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { repeating = true, locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { repeating = true, locked = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { repeating = true, locked = true })

-- Brightness keys

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { repeating = true, locked = true })

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { repeating = true, locked = true })

-- Audio

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
