-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--###############

--## MONITORS ###

--###############

hl.monitor({
    output   = "desc:BOE 0x088C",
    mode     = "preferred",
    position = "auto",
    scale    = 1.5,
})
