-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--##################

--## MY PROGRAMS ###

--##################

local terminal = "kitty"

local fileManager = "yazi"

local browser = "brave"

local IDE = "zeditor"

-- rofi

local searchApps = "rofi -show drun"

local searchWindows = "rofi -show window"

local selectWallpaper = "~/.dotfiles/.config/rofi/select-wallpaper.sh"

local openControlCenter = "rofi -show control-center -modi \"control-center:~/.dotfiles/.config/rofi/control-center.sh\""

local music = "brave https://open.spotify.com/"

local steam = steam
