-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- TODO: manual review: focus_on_activate = true

--#################################

--## DEFAULT CONFIG WINDOWRULES ###

--#################################

hl.window_rule({
    name  = "suppress-maximize-events",
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

hl.window_rule({
    name  = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    no_focus = true,
})

-- Hyprland-run windowrule

hl.window_rule({
    name  = "move-hyprland-run",
    match = {
        class = "hyprland-run",
    },
    move = { 20, "monitor_h-120" },
    float = true,
})

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

--###########################

--# FLOAT AND CENTER RULES ##

--###########################

hl.window_rule({
    name  = "float_on_43",
    match = {
        class = "^(org.gnome.Nautilus)$",
    },
    float = true,
    size = { 800, 600 },
    center = true,
})

hl.window_rule({
    name  = "center-file-manager-launch",
    match = {
        initial_class = "^(kitty)$",
        title = "^(yazi)$",
    },
    float = true,
    center = true,
    size = { 880, 580 },
})

hl.window_rule({
    name  = "center-file-manager-open",
    match = {
        initial_class = "^(kitty)$",
        title = "^(termfilechooser)$",
    },
    float = true,
    center = true,
    size = { 880, 580 },
})

hl.window_rule({
    name  = "center-wifi-menu",
    match = {
        initial_class = "^(kitty)$",
        initial_title = "^(impala)$",
        title = "^(impala)$",
    },
    float = true,
    center = true,
    size = { 752, 580 },
})

hl.window_rule({
    name  = "center-bluetooth-menu",
    match = {
        initial_class = "^(kitty)$",
        initial_title = "^(bluetui)$",
    },
    float = true,
    center = true,
    size = { 752, 580 },
})

hl.window_rule({
    name  = "center-audio-menu",
    match = {
        initial_class = "^(kitty)$",
        initial_title = "^(wiremix)$",
    },
    float = true,
    center = true,
    size = { 600, 250 },
})

hl.window_rule({
    name  = "center-update-menu",
    match = {
        initial_class = "^(kitty)$",
        initial_title = "^(update-system)$",
    },
    float = true,
    center = true,
    size = { 752, 580 },
})

-- Fullscreen on launch

hl.window_rule({
    name  = "center-system-menu",
    match = {
        initial_class = "^(kitty)$",
        initial_title = "^(btop)$",
    },
    float = true,
    center = true,
    size = { 1220, 630 },
})

hl.window_rule({
    name  = "center-zed-settings",
    match = {
        class = "^(dev.zed.Zed)$",
        title = "^(Zed — Settings)$",
    },
    float = true,
    size = { 1000, 600 },
    center = true,
})
