###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = nautilus
$searchApps = rofi -show drun
$searchWindows = rofi -show window
# $controlCenter = 0 Will implement after menus are complete
$browser = brave
$IDE = zeditor

$storage = baobab
$systemMonitor = gnome-system-monitor

$music = spotify
$steam = steam
