###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = nautilus

$browser = brave
$IDE = zeditor

# rofi
$searchApps = rofi -show drun
$searchWindows = rofi -show window
$selectWallpaper = ~/.dotfiles/.config/rofi/control-center/select-wallpaper.sh

# "Do not launch rofi from inside rofi
$openControlCenter = rofi -show controls -modi "controls:~/.dotfiles/.config/rofi/control-center/open-controls.sh"

$storage = baobab
$systemMonitor = gnome-system-monitor

$music = spotify
$steam = steam
