###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = nautilus

$browser = brave
$IDE = zeditor

# rofi
$searchApps = rofi -show drun
$searchWindows = rofi -show window
$bluetooth = ~/.dotfiles/.config/rofi/control-center/rofi-bluetooth.sh
$selectWallpaper = ~/.dotfiles/.config/rofi/control-center/rofi-select-wallpaper.sh
# $controlCenter = 0 Will implement after menus are complete

$storage = baobab
$systemMonitor = gnome-system-monitor

$music = spotify
$steam = steam
