focus_on_activate = true

##################################
### DEFAULT CONFIG WINDOWRULES ###
##################################

windowrule {
    # Ignore maximize requests from all apps
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

xwayland {
	force_zero_scaling = true
}

############################
## FLOAT AND CENTER RULES ##
############################

# Gnome Apps
windowrule = match:class ^(org.gnome.Nautilus)$, float on, size 800 600, center on
windowrule = match:class ^(org.gnome.baobab)$, float on, size 1200 650, center on
windowrule = match:class ^(org.gnome.SystemMonitor)$, float on, size 1200 650, center on

# Zed Settings Screen
windowrule {
    name = center-zed-settings
    match:class = ^(dev.zed.Zed)$
    match:title = ^(Zed — Settings)$
    float = on
    size = 1000 600
    center = on
}

################
## FULLSCREEN ##
################

# Fullscreen on launch
windowrule = match:class ^(Spotify)$, fullscreen_state 2
windowrule = match:class ^(steam)$, fullscreen_state 1
