focus_on_activate = true

##################################
### DEFAULT CONFIG WINDOWRULES ###
##################################

windowrule {
    # Ignore maximize requests from all apps
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

xwayland {
	force_zero_scaling = true
}

############################
## FLOAT AND CENTER RULES ##
############################

windowrule = match:class ^(org.gnome.Nautilus)$, float on, size 800 600, center on

# CONTROL CENTER WINDOW RULES ARE NOT WORKING.
# Likely an issue caused by runnning them through Rofi
windowrule {
    name = center-wifi-menu
    match:initial_class = ^(kitty)$
    match:initial_title = ^(impala)$
    match:title = ^(impala)$
    float = on
    center = on
    size = 752 580
}

windowrule {
    name = center-bluetooth-menu
    match:initial_title = ^(kitty)$
    match:title = ^(bluetui)$
    float = on
    center = on
    size = 752 580
}

# Zed Settings Screen
windowrule {
    name = center-zed-settings
    match:class = ^(dev.zed.Zed)$
    match:title = ^(Zed — Settings)$
    float = on
    size = 1000 600
    center = on
}

################
## FULLSCREEN ##
################

# Fullscreen on launch
windowrule = match:class ^(Spotify)$, fullscreen_state 2
windowrule = match:class ^(steam)$, fullscreen_state 1
