focus_on_activate = true

##################################
### DEFAULT CONFIG WINDOWRULES ###
##################################

windowrule {
    # Ignore maximize requests from all apps
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

xwayland {
	force_zero_scaling = true
}

############################
## FLOAT AND CENTER RULES ##
############################

windowrule = match:class ^(org.gnome.Nautilus)$, float on, size 800 600, center on
windowrule {
    name = center-file-manager-launch
    match:initial_class = ^(kitty)$
    match:title = ^(yazi)$
    float = on
    center = on
    size = 880 580
}

windowrule {
    name = center-file-manager-open
    match:initial_class = ^(kitty)$
    match:title = ^(termfilechooser)$
    float = on
    center = on
    size = 880 580
}

windowrule {
    name = center-wifi-menu
    match:initial_class = ^(kitty)$
    match:initial_title = ^(impala)$
    match:title = ^(impala)$
    float = on
    center = on
    size = 752 580
}

windowrule {
    name = center-bluetooth-menu
    match:initial_class = ^(kitty)$
    match:initial_title = ^(bluetui)$
    float = on
    center = on
    size = 752 580
}

windowrule {
    name = center-audio-menu
    match:initial_class = ^(kitty)$
    match:initial_title = ^(wiremix)$
    float = on
    center = on
    size = 600 250
}

windowrule {
    name = center-update-menu
    match:initial_class = ^(kitty)$
    match:initial_title = ^(update-system)$
    float = on
    center = on
    size = 752 580
}

# Fullscreen on launch
windowrule {
    name = center-system-menu
    match:initial_class = ^(kitty)$
    match:initial_title = ^(btop)$
    float = on
    center = on
    size = 1220 630
}


windowrule {
    name = center-zed-settings
    match:class = ^(dev.zed.Zed)$
    match:title = ^(Zed — Settings)$
    float = on
    size = 1000 600
    center = on
}
